### ISSUE TITLE
Non-integer builds

### ISSUE THREAD

**Issue by cviebrock** [HausennTechnologies/capacitor-set-version#187]
I thought I could do something clever like:

```
capacitor-set-version -b $(git rev-parse --short HEAD) 
```

But I get back the error: `Error: Expected an integer but received: 140eb04`

I'm pretty sure the build for iOS doesn't need to be an integer, but I could be wrong.  I'm also not sure at all about Android.  If possible, any chance you can allow non-integer values for the build version?

**Comment by DKrepsky** [comment]
Hi @cviebrock

You are right about iOS, it can be any string. For Android, it must be an integer greater than the last version published.

So, I can add to accept any string when the iOS only flag is passed, but not for android.

If you think it will help you and others by accepting strings for iOS, leave a comment and I'll do my best to have this soon.

Btw, we're using this tool along with [Semantic Release](https://github.com/semantic-release/semantic-release) for automatic versioning, so keeping both android and iOS build numbers as an incremental number is very handy.

Regards ;D

**Comment by cviebrock** [comment]
If Android only accepts integers, then it's probably best to just leave it as-is, to make it more cross-platform friendly.

Thanks!
