### ISSUE TITLE
Reopen issue build number (CFBundleVersion) as integer in XCode instead of string

### ISSUE THREAD

**Issue by xzetic05** [HausennTechnologies/capacitor-set-version#215]
on latest v2.0.0 it seems the [issue 159](https://github.com/HausennTechnologies/capacitor-set-version/issues/159) has been reopen because the value of CFBundleVersion showing as <integer><integer> and because of that it resulted to iOS App Crash.

**Comment by DKrepsky** [comment]
Indeed, this is a regression bug.

I'll fix it now.
