### ISSUE TITLE
Error: Invalid android settings: null:null

### ISSUE THREAD

**Issue by syphernl** [HausennTechnologies/capacitor-set-version#76]
Running `npx capacitor-set-version -v 1.2.3 ./` on a ionic/capacitor project results in:

```
❯ npx capacitor-set-version -v 1.2.3 ./
version: 1.2.3
 ›   Error: Invalid android settings: null:null
```

It seems that it is trying to access a value that is not in the configuration, resulting in the `null` response. It would be nice if this tool could mention what it is looking for, so it can be added.

**Comment by DKrepsky** [comment]
Hi,

I'm working on better error handling and more descriptive error messages, should come out soon.

Thanks for the feedback.
